export const TableData: Array<any> = [

  {
    "case": 1,
    "patient": '51 year old male',
    "age": 51,
    "gender": "Male",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Local transmission",
    "symptomaticToConfirmation": 12,
    "daysToRecover": 8,
    "symptomaticAt": "4th Mar 2020",
    "confirmedAt": "5th Mar 2020",
    "recoveredAt": "12th Mar 2020",
    "displayedSymptoms": true
  },
  {
    "case": 2,
    "patient": '67 year old female',
    "age": 67,
    "gender": "Female",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Imported case",
    "symptomaticToConfirmation": 4,
    "daysToRecover": 12,
    "symptomaticAt": "21st Feb 2020",
    "confirmedAt": "26th Feb 2020",
    "recoveredAt": "8th Mar 2020",
    "displayedSymptoms": false
  },
  {
    "case": 3,
    "patient": '51 year old male',
    "age": 51,
    "gender": "Male",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Local transmission",
    "symptomaticToConfirmation": 12,
    "daysToRecover": 8,
    "symptomaticAt": "4th Mar 2020",
    "confirmedAt": "5th Mar 2020",
    "recoveredAt": "12th Mar 2020",
    "displayedSymptoms": true
  },
  {
    "case": 4,
    "patient": '67 year old female',
    "age": 67,
    "gender": "Female",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Imported case",
    "symptomaticToConfirmation": 4,
    "daysToRecover": 12,
    "symptomaticAt": "21st Feb 2020",
    "confirmedAt": "26th Feb 2020",
    "recoveredAt": "8th Mar 2020",
    "displayedSymptoms": false
  },
  {
    "case": 5,
    "patient": '51 year old male',
    "age": 51,
    "gender": "Male",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Local transmission",
    "symptomaticToConfirmation": 12,
    "daysToRecover": 8,
    "symptomaticAt": "4th Mar 2020",
    "confirmedAt": "5th Mar 2020",
    "recoveredAt": "12th Mar 2020",
    "displayedSymptoms": true
  },
  {
    "case": 6,
    "patient": '67 year old female',
    "age": 67,
    "gender": "Female",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Imported case",
    "symptomaticToConfirmation": 4,
    "daysToRecover": 12,
    "symptomaticAt": "21st Feb 2020",
    "confirmedAt": "26th Feb 2020",
    "recoveredAt": "8th Mar 2020",
    "displayedSymptoms": false
  },
  {
    "case": 7,
    "patient": '51 year old male',
    "age": 51,
    "gender": "Male",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Local transmission",
    "symptomaticToConfirmation": 12,
    "daysToRecover": 8,
    "symptomaticAt": "4th Mar 2020",
    "confirmedAt": "5th Mar 2020",
    "recoveredAt": "12th Mar 2020",
    "displayedSymptoms": true
  },
  {
    "case": 8,
    "patient": '67 year old female',
    "age": 67,
    "gender": "Female",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Imported case",
    "symptomaticToConfirmation": 4,
    "daysToRecover": 12,
    "symptomaticAt": "21st Feb 2020",
    "confirmedAt": "26th Feb 2020",
    "recoveredAt": "8th Mar 2020",
    "displayedSymptoms": false
  },
  {
    "case": 9,
    "patient": '51 year old male',
    "age": 51,
    "gender": "Male",
    "nationality": "Indian",
    "status": "In Hospital",
    "infectionSource": "Local transmission",
    "symptomaticToConfirmation": 12,
    "daysToRecover": 8,
    "symptomaticAt": "4th Mar 2020",
    "confirmedAt": "5th Mar 2020",
    "recoveredAt": "12th Mar 2020",
    "displayedSymptoms": true
  }
];