name: Deploy website to GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
  # https://crontab.guru/every-30 minutes
  - cron: 30 4-20/1 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: |
         npm install -g @angular/cli
         npm i -g gzip-cli
         npm install
         ng build --prod
         npm run scully
         npm run staticgzip
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist/static
        COMMIT_MESSAGE: "Website last updated ${{steps.date.outputs.date}}"
        CLEAN: true
