name: Deploy website to GitHub Pages

on:
  push: 
    branches:   
      - master
  schedule:
  # https://crontab.guru/every-30 minutes
  - cron: 0/30 * * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: false
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build
      run: |
         npm install -g @angular/cli
         npm install
         ng build --prod
         ng config -g cli.warnings.versionMismatch false
         npm run scully -- --host='0.0.0.0'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/static
        COMMIT_MESSAGE: "Website last updated ${{steps.date.outputs.date}}"
